# Generated by Django 5.2.13 on 2026-05-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('BTech', 'BTech')], max_length=20)),
                ('previous_school', models.CharField(max_length=200)),
                ('marks', models.FloatField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('document', models.ImageField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
